name: feednet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  connectivity_plus: ^6.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_reaction_button: ^3.0.0+3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/feednet.png"
  min_sdk_android: 21  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
