// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeT7lLw0osb7Qmd2VlWjU-oze_GWnuFT0',
    appId: '1:532442428762:web:ffaf1318fa968f6d6a2f63',
    messagingSenderId: '532442428762',
    projectId: 'feednet-3b1bc',
    authDomain: 'feednet-3b1bc.firebaseapp.com',
    storageBucket: 'feednet-3b1bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIsWvf9Xy9-aNA9igWhdhYEvNQzVQFPeA',
    appId: '1:532442428762:android:eed292732358aabf6a2f63',
    messagingSenderId: '532442428762',
    projectId: 'feednet-3b1bc',
    storageBucket: 'feednet-3b1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbksKXvzqFbmt09XzedQvnpEKmbdOLxmg',
    appId: '1:532442428762:ios:d7b3dd3d4d8b0d9a6a2f63',
    messagingSenderId: '532442428762',
    projectId: 'feednet-3b1bc',
    storageBucket: 'feednet-3b1bc.firebasestorage.app',
    iosBundleId: 'com.example.feednet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbksKXvzqFbmt09XzedQvnpEKmbdOLxmg',
    appId: '1:532442428762:ios:d7b3dd3d4d8b0d9a6a2f63',
    messagingSenderId: '532442428762',
    projectId: 'feednet-3b1bc',
    storageBucket: 'feednet-3b1bc.firebasestorage.app',
    iosBundleId: 'com.example.feednet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeT7lLw0osb7Qmd2VlWjU-oze_GWnuFT0',
    appId: '1:532442428762:web:c260bb5422cc944a6a2f63',
    messagingSenderId: '532442428762',
    projectId: 'feednet-3b1bc',
    authDomain: 'feednet-3b1bc.firebaseapp.com',
    storageBucket: 'feednet-3b1bc.firebasestorage.app',
  );
}
